---
title: "<center>**Working with Diamonds Data**</center>"
author: "<center>Wyclife Agumba Oluoch (wyclifeoluoch@gmail.com) </center>"
date: "<center>`r Sys.time()`</center>"
bibliography: 
  - bib/packages.bib
nocite: '@*'
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
packages <- c("base",
              'knitr',
              'rmarkdown',
              'tidyverse',
              'RColorBrewer',
              'grDevices')
installed_packages <- packages %in% rownames(installed.packages())
if(any(installed_packages == FALSE)){
  install.packages(packages[!installed_packages])
}
lapply(packages, library, character.only = TRUE) |> invisible()
```

```{r write_bib, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::write_bib(c(
  .packages(), packages
), 'bib/packages.bib')
```

# Diamonds dataframe

```{r df}
diamonds_df <- diamonds
head(diamonds_df)
nrow(diamonds_df)
ncol(diamonds_df)
```

```{r diamonds_plot}
diamonds_df %>% # Picking the diamonds data, and th
  dplyr::slice_sample(n = 0.2*(nrow(diamonds))) %>% # Picking a portion of the data-set
  ggplot2::ggplot(ggplot2::aes(x = cut, y = price, color = cut)) + # Adding the mapping variables
  ggplot2::geom_point(position = "jitter", alpha = 0.2) + # Adding jitter and alpha
  ggplot2::geom_boxplot(alpha = 0.1, width = 0.5) + # Modifying dimensions of the boxplot 
  ggplot2::geom_violin(alpha = 0.5) + # Adding violin plot on top of the box and jitter
  ggplot2::theme_classic() + # Adding my preferred theme for publication.
  ggplot2::theme(legend.position = "none") +
  ggplot2::labs(x = "Diamond cut", # Labels the x-axis.
       y = "Diamonds price (USD)", # Labeling the y-axis
       title = "Diamond cut against price", # Setting tibble of the plot
       subtitle = "Preview of diamond cut versus price", # Descriptive title beneath TITLE
       caption = "Data source: gglot2 package's diamond data") +
  ggplot2::theme(axis.text = ggplot2::element_text(size=16), # Size of labels on tick-marks
        axis.title = ggplot2::element_text(size=16,face="bold")) + # Size of axis labels
  ggplot2::theme(plot.title = ggplot2::element_text(color = 'red', size = 18, face = 'bold'),
        plot.subtitle = ggplot2::element_text(color = 'purple', size = 14, face = 'italic'),
        plot.caption = ggplot2::element_text(color = 'blue', face = 'italic'))
```

# Simple Wrangling

```{r simple}
diamonds %>% # Picking the diamonds data, and then
  dplyr::filter(cut == 'Very Good') %>% # Picking the very good cut 
  base::nrow() # counting the number of rows with very good cut

diamonds %>% 
  dplyr::select(cut) %>% 
  base::table() %>% 
  graphics::barplot(col = c('green', 'red', 'blue', 'yellow', 'purple'))
```

# Using color brewer

```{r color_brewer}
diamonds %>% 
  dplyr::select(cut) %>% 
  base::table() %>% 
  graphics::barplot(col = RColorBrewer::brewer.pal(n = 5, name = "RdBu"))
# To display more brewer colors options to use, run the following function:

RColorBrewer::display.brewer.all()

# Can also use rainbow colors

diamonds %>% 
  dplyr::select(cut) %>% 
  base::table() %>% 
  graphics::barplot(col = rainbow(5, alpha = 1))

# Can also use heat.colors
diamonds %>% 
  dplyr::select(cut) %>% 
  base::table() %>% 
  graphics::barplot(col = heat.colors(5, alpha = 1))

# Can also use topographic colors

diamonds %>% 
  dplyr::select(cut) %>% 
  base::table() %>% 
  graphics::barplot(col = topo.colors(5, alpha = 1))

# Can also use terrain colors for the plot
diamonds %>% 
  dplyr::select(cut) %>% 
  base::table() %>% 
  graphics::barplot(col = terrain.colors(5, alpha = 1))

# Can also use cm.colors
diamonds %>% 
  dplyr::select(cut) %>% 
  base::table() %>% 
  graphics::barplot(col = cm.colors(5, alpha = 1)) 

```

# References