---
title: "<center>**Mathematical equations in R Markdown**</center>"
author: "<center>Wyclife Agumba Oluoch (wyclifeoluoch@gmail.com) </center>"
date: "<center>`r Sys.time()`</center>"
bibliography: 
  - bib/packages.bib
nocite: '@*'
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
packages <- c("base",
              'knitr',
              'rmarkdown')
installed_packages <- packages %in% rownames(installed.packages())
if(any(installed_packages == FALSE)){
  install.packages(packages[!installed_packages])
}
lapply(packages, library, character.only = TRUE) |> invisible()
```

```{r write_bib, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::write_bib(c(
  .packages(), packages
), 'bib/packages.bib')
```


# Mathematics Equations

Writing mathematical equations can be a daunting endeavor in R Markdown. Here I provide them as provided [here](https://rpruim.github.io/s341/S19/from-class/MathinRmd.html)



# References