---
title: "<center>**Raincloud plot in R**</center>"
author: "<center>Wyclife Agumba Oluoch (wyclifeoluoch@gmail.com) </center>"
date: "<center>`r Sys.time()`</center>"
bibliography: 
  - bib/packages.bib
nocite: '@*'
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
packages <- c("base",
          'knitr',
              'rmarkdown',
              'tidyverse',
              'ggdist',
              'ggtext',
              'gapminder',
              'glue')
installed_packages <- packages %in% rownames(installed.packages())
if(any(installed_packages == FALSE)){
  install.packages(packages[!installed_packages])
}
lapply(packages, library, character.only = TRUE) |> invisible()
```

```{r write_bib, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::write_bib(c(
  .packages(), packages
), 'bib/packages.bib')
```

# Introduction

In this short article I demonstrate how to generate beautiful plots using a number of packages in R. For the .Rmd file containing codes that generated the plot visit my [gitHUb](https://github.com/Wycology/repoforrstudio/blob/main/raincloud.Rmd) page.

```{r echo=FALSE}
annotation <- base::data.frame(x = 4.5, y = 35,
                   label = c(glue("The data is from the <br> gapminder package<br> which you can easily install")))

gapminder |>
  select(continent, lifeExp) |>
  ggplot(aes(continent, lifeExp)) +
  stat_halfeye(
    adjust = .5,
    width = .6,
    .width = 0,
    justification = -.2,
    point_color = NA,
    aes(fill = continent)
  ) +
  geom_boxplot(width = .12, outlier.shape = NA) +
  stat_dots(
    side = 'left',
    justification = 1.1,
    binwidth = 0.5,
    aes(col = continent)
  ) +
  geom_richtext(
    data = annotation,
    aes(x = x, y = y, label = label),
    color = 'orange',
    size = 7,
    angle = 0,
    fontface = 'bold'
  ) +
  labs(
    title = 'Distribution of life expectancy in five continents',
    subtitle = 'Between 1952 and 2007',
    caption = paste0(
      'Source: Data from gapminder, Version ',
      packageVersion('gapminder')
    ),
    x = 'Continent',
    y = 'Life expectancy (years)'
  ) +
  coord_cartesian(xlim = c(0.6, NA)) +
  theme_classic() +
  theme(legend.position = 'none',
        text = element_text(size = 18)) 
```

# References
