---
title: "<center>**Read_Write_csv in R**</center>"
author: "<center>Wyclife Agumba Oluoch (wyclifeoluoch@gmail.com) </center>"
date: "<center>`r Sys.time()`</center>"
bibliography: 
  - bib/packages.bib
nocite: '@*'
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
packages <- c("base",'knitr','rmarkdown',
              'dplyr',
              'plyr',
              'readr')
installed_packages <- packages %in% rownames(installed.packages())
if(any(installed_packages == FALSE)){
  install.packages(packages[!installed_packages])
}
lapply(packages, library, character.only = TRUE) |> invisible()
```

```{r write_bib, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
knitr::write_bib(c(
  .packages(), packages
), 'bib/packages.bib')
```

# Reading multiple csv files into R

```{r read}
my_csv_files <- base::list.files(path = 'D:/FILES', 
                           pattern = "*.csv", 
                           full.names = TRUE) %>% 
  base::lapply(readr::read_csv) %>% 
  dplyr::bind_cols() %>% 
  dplyr::select(A...1, B...2, E...5)
```


# Writing to multiple sheets of csv

```{r write}
readr::write_csv(my_csv_files, 'my_columns.csv', progress = TRUE)
```


# References
