---
title: "<center>**Parametric and non-parametric t-tests in R**</center>"
author: "<center>Wyclife Agumba Oluoch (wyclifeoluoch@gmail.com) </center>"
date: "<center>`r Sys.time()`</center>"
bibliography: 
  - bib/packages.bib
nocite: '@*'
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(base)
library(knitr)
library(rmarkdown)
library(utils)
library(stats)
library(nortest)
library(car)
library(mapsf)
library(mapview)
knitr::write_bib(c(.packages(),
                   'base',
                   'knitr',
                   'rmarkdown',
                   'utils',
                   'stats',
                   'nortest',
                   'car',
                   'mapsf',
                   'mapview'), 'bib/packages.bib')
```

# Creating the dataset

```{r dataset, echo = FALSE}
data_set <- data.frame(Gender = c(rep('Male', 100), rep('Female', 100)),
                   abundance = sample(x = 7:40, size = 200, replace = TRUE))
```

# Checking for normality

## Using qqnorm and qqline

```{r normality_check_qq}
qqnorm(data_set$abundance)
qqline(data_set$abundance)
```

## Using Shapiro test

```{r normality_check_shapiro}
shapiro.test(data_set$abundance)
```

p<a hence we reject the null hypothesis and conclude that the data is no-parametric

## Using Anderson-Darling test

```{r normality_check_Anderson_Darling}

```


# References